// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAaf_nbGpXShwuthvQZ23ZLiGcvMCN82o0',
    appId: '1:857412161759:web:d814def8a71851c636596a',
    messagingSenderId: '857412161759',
    projectId: 'fitnessworkoutapp-601c0',
    authDomain: 'fitnessworkoutapp-601c0.firebaseapp.com',
    databaseURL: 'https://fitnessworkoutapp-601c0-default-rtdb.firebaseio.com',
    storageBucket: 'fitnessworkoutapp-601c0.appspot.com',
    measurementId: 'G-34CNE3XTXM',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyABvXtc7ccj6zIaYgm2XZ-UFI3MPDt-T5o',
    appId: '1:857412161759:android:a713f7811b26427336596a',
    messagingSenderId: '857412161759',
    projectId: 'fitnessworkoutapp-601c0',
    databaseURL: 'https://fitnessworkoutapp-601c0-default-rtdb.firebaseio.com',
    storageBucket: 'fitnessworkoutapp-601c0.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC0iHZ0iiXpUklGA1SRmyr7kFGAZuynDfs',
    appId: '1:857412161759:ios:d5c0fb3132523a2e36596a',
    messagingSenderId: '857412161759',
    projectId: 'fitnessworkoutapp-601c0',
    databaseURL: 'https://fitnessworkoutapp-601c0-default-rtdb.firebaseio.com',
    storageBucket: 'fitnessworkoutapp-601c0.appspot.com',
    androidClientId: '857412161759-pljr60681mmis7b9lojsbuifff1qriar.apps.googleusercontent.com',
    iosClientId: '857412161759-h70t3kg32cg2hfvds9ej5o99vto8cba7.apps.googleusercontent.com',
    iosBundleId: 'com.example.geminiGpt',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC0iHZ0iiXpUklGA1SRmyr7kFGAZuynDfs',
    appId: '1:857412161759:ios:d5c0fb3132523a2e36596a',
    messagingSenderId: '857412161759',
    projectId: 'fitnessworkoutapp-601c0',
    databaseURL: 'https://fitnessworkoutapp-601c0-default-rtdb.firebaseio.com',
    storageBucket: 'fitnessworkoutapp-601c0.appspot.com',
    androidClientId: '857412161759-pljr60681mmis7b9lojsbuifff1qriar.apps.googleusercontent.com',
    iosClientId: '857412161759-h70t3kg32cg2hfvds9ej5o99vto8cba7.apps.googleusercontent.com',
    iosBundleId: 'com.example.geminiGpt',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCAmthwHpduh4Uwr-fqjDJi0q7ioydSA_g',
    appId: '1:857412161759:web:c3d25334f5bd6d1636596a',
    messagingSenderId: '857412161759',
    projectId: 'fitnessworkoutapp-601c0',
    authDomain: 'fitnessworkoutapp-601c0.firebaseapp.com',
    databaseURL: 'https://fitnessworkoutapp-601c0-default-rtdb.firebaseio.com',
    storageBucket: 'fitnessworkoutapp-601c0.appspot.com',
    measurementId: 'G-NN8L7235GV',
  );
}
